### ISSUE TITLE
License for project.

### ISSUE THREAD

**Issue by erichexter** [danludwig/BeginCollectionItem#7]
Any chance you can declare a license for this project?

**Comment by hazzik** [comment]
@erichexter it's Ms-PL. It's in the [readme](https://github.com/danludwig/BeginCollectionItem/blob/master/README.md#license).

>**License**
>This software is subject to the terms of the [Microsoft Public License (Ms-PL)](http://www.opensource.org/licenses/MS-PL).

**Comment by erichexter** [comment]
I am sorry, I thought I searched before opening the ticket. My apologies.
