### ISSUE TITLE
BeginCollectionItem is rendering list tags, is it right?

### ISSUE THREAD

**Issue by DouglasCBO** [danludwig/BeginCollectionItem#9]
When I use `@using BeginCollectionItem('ListName')`, it renders my itens inside `<ul>` and `<li>` elements. Why? Is there a way to remove that?

**Comment by hazzik** [comment]
You can change the behaviour by replacing [Collection.chtml template](https://github.com/danludwig/BeginCollectionItem/blob/master/BeginCollectionItem.Mvc3Demo/Views/Shared/EditorTemplates/Collection.cshtml) (put it in `Views/Shared/EditorTemplates/Collection.cshtml`)

**Comment by DouglasCBO** [comment]
Thank you
